version: '3.8'

services:
  next:
    container_name: rband-next
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: pnpm dev
